### ISSUE TITLE
 Issue with Rukki: thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1'

### ISSUE THREAD

**Issue by XingzhengLee** [marbl/verkko#225]
Hello,

Briefly, the Snakemake workflow encountered issues on the server I am using. Nevertheless, I devised a workaround by manually executing each step, guided by the error messages and corresponding commands in the log file. The process proceeded smoothly until reaching the rukki.sh step.

### Command (encountering error): 

```
#
#  Run Rukki.  Once for Bandage input, once for Consensus.
#

params=""
params="$params --init-assign out_init_ann.csv"
params="$params --refined-assign out_refined_ann.csv"
params="$params --final-assign out_final_ann.csv"
params="$params --marker-sparsity 10000"
params="$params --marker-cnt 20"
params="$params --issue-sparsity 1000"
params="$params --try-fill-bubbles"
params="$params --fillable-bubble-diff 1000"
params="$params --fillable-bubble-len 500000"
params="$params --assign-tangles --tangle-allow-deadend"
params="$params --issue-ratio 1."
params="$params --solid-homozygous-cov-coeff 1.1"
params="$params --solid-ratio 1.01"
params="$params --hap-names $label1,$label2"

if [ xtrio = xtrio ]; then
   params="$params --marker-ratio 5."
   params="$params --tangle-prevent-reassign"
else
   params="$params --marker-ratio 3."
fi

echo "Rukki parameters:"
echo "  $params"
echo ""

echo "Bandage run:"
echo ""
~/miniconda3/envs/verkko/lib/verkko/bin/rukki trio -g ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.noseq.gfa -m ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.colors.csv -p ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.paths.tsv $params  && echo "** 6 done **"
echo ""

echo "Consensus run:"
echo ""
~/miniconda3/envs/verkko/lib/verkko/bin/rukki trio -g ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.noseq.gfa -m ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.colors.csv --gaf-format -p ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.paths.gaf $params && echo "** 7 done **"
echo ""
```

### Error message:

```
2024-01-14T13:14:22Z INFO  rukki] Running trio marker analysis
[2024-01-14T13:14:22Z INFO  rukki] Reading graph from ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.noseq.gfa
[2024-01-14T13:14:22Z INFO  rukki] Graph read successfully
[2024-01-14T13:14:22Z INFO  rukki] Node count: 8797
[2024-01-14T13:14:22Z INFO  rukki] Link count: 11170
[2024-01-14T13:14:22Z INFO  rukki] Reading trio marker information from ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.colors.csv
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/trio.rs:89:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Detailed information:

```
2024-01-14T13:15:11Z INFO  rukki] Running trio marker analysis
[2024-01-14T13:15:11Z INFO  rukki] Reading graph from ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.noseq.gfa
[2024-01-14T13:15:12Z INFO  rukki] Graph read successfully
[2024-01-14T13:15:12Z INFO  rukki] Node count: 8797
[2024-01-14T13:15:12Z INFO  rukki] Link count: 11170
[2024-01-14T13:15:12Z INFO  rukki] Reading trio marker information from ../6-rukki/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.colors.csv
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/trio.rs:89:30
stack backtrace:
   0:     0x55ab4082dc91 - std::backtrace_rs::backtrace::libunwind::trace::h782cc21a5acaf6cb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ab4082dc91 - std::backtrace_rs::backtrace::trace_unsynchronized::hc579eb24ab204515
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ab4082dc91 - std::sys_common::backtrace::_print_fmt::h7223525cfdbacda2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55ab4082dc91 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd7d55b7108d2ab8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55ab408504ef - core::fmt::rt::Argument::fmt::hb4f4a02b9bd9dd49
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:     0x55ab408504ef - core::fmt::write::h6d54cd7c9e155ec5
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:     0x55ab4082bd61 - std::io::Write::write_fmt::h6a453a71c692f63b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:     0x55ab4082daa5 - std::sys_common::backtrace::_print::h1cbaa8b42678f928
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55ab4082daa5 - std::sys_common::backtrace::print::h4ddf81241a51b337
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55ab4082ee27 - std::panicking::default_hook::{{closure}}::hff91f1f484ade5cd
  10:     0x55ab4082ec14 - std::panicking::default_hook::h21f14afd59f7aef9
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:     0x55ab4082f2dc - std::panicking::rust_panic_with_hook::h45f66047b14c555c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:705:13
  12:     0x55ab4082f1d7 - std::panicking::begin_panic_handler::{{closure}}::h49d1a88ef0908eb4
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:597:13
  13:     0x55ab4082e0c6 - std::sys_common::backtrace::__rust_end_short_backtrace::hccebf9e57f8cc425
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55ab4082ef22 - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  15:     0x55ab406be583 - core::panicking::panic_fmt::h54ec9d0e3180a83d
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
  16:     0x55ab406be6e2 - core::panicking::panic_bounds_check::h7d0e683548e4cb10
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:162:5
  17:     0x55ab406fce52 - rukki::trio::read_trio::hb2986b3cf3e91c40
  18:     0x55ab406cc779 - rukki::run_trio_analysis::h3c13268476bf2483
  19:     0x55ab406c46b8 - rukki::main::hf3b9fa0eda576132
  20:     0x55ab406c1793 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3efefcaef8ff4a7c
  21:     0x55ab406c1309 - std::rt::lang_start::{{closure}}::h6fbc2ecf3919b762
  22:     0x55ab40826c35 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h802b0fdd426a12ca
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:284:13
  23:     0x55ab40826c35 - std::panicking::try::do_call::h2a2f25050efa0cf8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  24:     0x55ab40826c35 - std::panicking::try::h9ca7f841c0f0e3dd
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  25:     0x55ab40826c35 - std::panic::catch_unwind::h92d42a62587f8121
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  26:     0x55ab40826c35 - std::rt::lang_start_internal::{{closure}}::hf1926c7a173d562c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:48
  27:     0x55ab40826c35 - std::panicking::try::do_call::haac70d88f0cce898
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
  28:     0x55ab40826c35 - std::panicking::try::h5c20719e1031e74b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
  29:     0x55ab40826c35 - std::panic::catch_unwind::h9b15b36860d5fe4a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
  30:     0x55ab40826c35 - std::rt::lang_start_internal::hf502095b101390bb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:20
  31:     0x55ab406c5005 - main
  32:     0x7f1e2f39a555 - __libc_start_main
  33:     0x55ab406bece5 - <unknown>
```

It seems that Rukki is not functioning as expected. However, I am uncertain whether the issue lies with Rukki itself or if the $params variable is not configured correctly. Any insights or suggestions would be greatly appreciated.

Thank you for your time and assistance!

[unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.zip](https://github.com/marbl/verkko/files/13934153/unitig-unrolled-unitig-unrolled-popped-unitig-normal-connected-tip.zip)

**Comment by skoren** [comment]
I  would again strongly recommend against running the pipeline outside of snakemake, it is non-trivial to get all the steps right and you'll likely encounter strange errors because of incorrect/missing outputs. You might even get an assembly but it would be not equal to what you got if you ran the entire pipeline through snakemake (say if you missed/ran a simplification step incorrectly). Snakemake should work on most systems so I would contact your IT dept and try to get snakemake to run on your cluster instead.

In this case, your csv is malformed because the first line is not using tab separators but instead spaces. Rukki expects these to be a tab-delimited file. Once that line is fixed, rukki runs on this input data.

**Comment by XingzhengLee** [comment]
Thank you for your valuable suggestions. While using Snakemake might indeed streamline the process, I opted to continue with my current approach since I was close to achieving the desired outcome. I appreciate your guidance, and I plan to explore Snakemake for future runs of Verkko, taking advantage of the time-saving benefits it offers.

Your information about Rukki was incredibly helpful, and the tool worked seamlessly after fixing the file format. The parse error originating from space separators in the tab-delimited file was a key insight.

`"node	mat	pat	mat:pat	color"`
to
`"node\tmat\tpat\tmat:pat\tcolor"`
works well for me. Regarding the file extension, either .tsv or .txt would be appropriate since the content is tab-delimited.

On another note, I successfully obtained two phased assemblies with considerable quality, featuring an N50 of around 60 Mb for a total size of approximately 2.5 GB. However, I observed that the assembly contains gaps which was uncommon for a primary assembly according to what I know. Could you clarify whether it's normal for Verkko to produce assemblies with "N"s indicating gaps?

**Comment by skoren** [comment]
There is primary assembly in a trio or Hi-C phased result. A trio will sort the chromosomes by parent of origin, independent of their quality. The gaps are introduced when there is either a tangle that cannot be resolved or there is a gap in one haplotype vs the other. The `*paths.tsv` in the top level provides more information on what was the reason for the gap:
```
mat_from_utig4-730      utig4-1740-,utig4-1727-,[N1000N:alt-utig4-720],utig4-730+       MAT
pat_from_utig4-47       utig4-93-,utig4-95+,[N5000N:ambig_path],utig4-43+,utig4-47+     PAT
```
The first line has a gap because there is a haplotype-gap in the maternal assembly corresponding to paternal utig4-720 and the second line has a gap because there is an abmgious path (e.g. more than one traversal) between nodes utig4-95 and utig4-43. Verkko is designed to be relatively conservative so sometime the ambiguous path is just an unpopped bubble or similar. If you want to, you can manually inspect the graph (`*.noseq.gfa`) output by verkko and, if you decide on a resolution, you can update the paths.tsv file with your selections and run verkko to generate a new consensus without those gaps you've resolved (see the verkko --paths option).

**Comment by XingzhengLee** [comment]
That clears up my uncertainty. Thank you for the detailed explanation!
