### ISSUE TITLE
problem with aligning tips 

### ISSUE THREAD

**Issue by luanelandau** [marbl/verkko#281]
I am trying to run verkko for a couple months now using trios. I have used HG01946, HG01944, and HG01945 short reads to generate the hapmers. This is the command line I am using:

```
par1="/projects/academic/omergokc/Luane/HG01946/verkko/maternal_compressed.k30.hapmer.meryl"
par2="/projects/academic/omergokc/Luane/HG01946/verkko/paternal_compressed.k30.hapmer.meryl"

#c.	For diploid inputs (with parental data):

#this step is for unlocking the folder and resuming the run
verkko -d HG01946_verkko_aug29 --hifi ${reads} --nano ${raw} --local-memory 900 --local-cpus 32 --snakeopts "--unlock" --cleanup --hap-kmers $par1 $par2 trio

#resuming the run
verkko -d HG01946_verkko_aug29 --hifi ${reads} --nano ${raw} --local-memory 900 --local-cpus 32 --cleanup --hap-kmers $par1 $par2 trio
```

The complete script is here
[verkko.sh.txt](https://github.com/user-attachments/files/16897064/verkko.sh.txt)

I got this error I have no idea what it is, so any help would be great. 

```
[Tue Sep  3 21:07:33 2024]
checkpoint splitTipsONT:
    input: /projects/academic/omergokc/Luane/HG01946/HG01946_allreads_Apr16.fastq, 2-processGraph/unitig-unrolled-hifi-resolved.gfa, 3-align/alns-ont.gaf, 3-align/splitONT.finished
    output: 3-alignTips/splitONT.finished
    log: 3-alignTips/splitONT.err
    jobid: 103
    reason: Missing output files: 3-alignTips/splitONT.finished; Input files updated by another job: 3-align/alns-ont.gaf
    resources: tmpdir=/scratch/17045552, job_id=1, n_cpus=1, mem_gb=8, time_h=96
Downstream jobs will be updated after completion.

[Tue Sep  3 21:07:33 2024]
Error in rule splitTipsONT:
    jobid: 103
    input: /projects/academic/omergokc/Luane/HG01946/HG01946_allreads_Apr16.fastq, 2-processGraph/unitig-unrolled-hifi-resolved.gfa, 3-align/alns-ont.gaf, 3-align/splitONT.finished
    output: 3-alignTips/splitONT.finished
    log: 3-alignTips/splitONT.err (check log file(s) for error message)
    shell:
        
cd 3-alignTips

cat > ./splitONT.sh <<EOF
#!/bin/sh
set -e -o pipefail

mkdir -p split

 /projects/academic/omergokc/Luane/conda/envs/herro/lib/verkko/scripts/find_tips.py ../2-processGraph/unitig-unrolled-hifi-resolved.gfa > tips.fasta 2> find_tips.err
awk '/^>/ { print substr(\$1, 2) }' < tips.fasta > tips.ids
cat ../3-align/alns-ont.gaf |  /projects/academic/omergokc/Luane/conda/envs/herro/lib/verkko/scripts/filter_alignments_by_column.py tips.ids 5 false | awk -F "\t" '{ if (\$12 >= 20) print \$1;}' | sort |uniq > tip_reads.ids

for fn in ont001.fasta.gz ont002.fasta.gz ont003.fasta.gz ont004.fasta.gz ont005.fasta.gz ont006.fasta.gz ont007.fasta.gz ont008.fasta.gz ont009.fasta.gz ont010.fasta.gz ont011.fasta.gz ont012.fasta.gz ont013.fasta.gz ont014.fasta.gz ont015.fasta.gz ont016.fasta.gz ont017.fasta.gz ont018.fasta.gz ont019.fasta.gz ont020.fasta.gz ont021.fasta.gz ont022.fasta.gz ont023.fasta.gz ont024.fasta.gz ont025.fasta.gz ont026.fasta.gz ont027.fasta.gz ont028.fasta.gz ont029.fasta.gz ont030.fasta.gz ont031.fasta.gz ont032.fasta.gz ont033.fasta.gz ont034.fasta.gz ont035.fasta.gz ont036.fasta.gz ont037.fasta.gz ont038.fasta.gz ont039.fasta.gz ont040.fasta.gz ont041.fasta.gz ont042.fasta.gz ont043.fasta.gz ont044.fasta.gz ont045.fasta.gz ont046.fasta.gz ont047.fasta.gz ont048.fasta.gz ont049.fasta.gz ont050.fasta.gz ont051.fasta.gz ont052.fasta.gz ont053.fasta.gz ont054.fasta.gz ont055.fasta.gz ont056.fasta.gz ont057.fasta.gz ont058.fasta.gz ont059.fasta.gz ont060.fasta.gz ont061.fasta.gz ont062.fasta.gz ont063.fasta.gz ont064.fasta.gz ont065.fasta.gz ont066.fasta.gz ont067.fasta.gz ont068.fasta.gz ont069.fasta.gz ont070.fasta.gz ont071.fasta.gz ont072.fasta.gz ont073.fasta.gz ont074.fasta.gz ont075.fasta.gz ont076.fasta.gz ont077.fasta.gz ont078.fasta.gz ont079.fasta.gz ont080.fasta.gz ont081.fasta.gz ont082.fasta.gz ont083.fasta.gz ont084.fasta.gz ont085.fasta.gz ont086.fasta.gz ont087.fasta.gz ; do
  echo >> tip_reads.extract extract \$fn tip_reads.ids ../3-align/split/\$fn
done

xargs -L 1 -P 1 < tip_reads.extract \\
   /projects/academic/omergokc/Luane/conda/envs/herro/lib/verkko/scripts/fasta_extract.py

gunzip -c ont001.fasta.gz ont002.fasta.gz ont003.fasta.gz ont004.fasta.gz ont005.fasta.gz ont006.fasta.gz ont007.fasta.gz ont008.fasta.gz ont009.fasta.gz ont010.fasta.gz ont011.fasta.gz ont012.fasta.gz ont013.fasta.gz ont014.fasta.gz ont015.fasta.gz ont016.fasta.gz ont017.fasta.gz ont018.fasta.gz ont019.fasta.gz ont020.fasta.gz ont021.fasta.gz ont022.fasta.gz ont023.fasta.gz ont024.fasta.gz ont025.fasta.gz ont026.fasta.gz ont027.fasta.gz ont028.fasta.gz ont029.fasta.gz ont030.fasta.gz ont031.fasta.gz ont032.fasta.gz ont033.fasta.gz ont034.fasta.gz ont035.fasta.gz ont036.fasta.gz ont037.fasta.gz ont038.fasta.gz ont039.fasta.gz ont040.fasta.gz ont041.fasta.gz ont042.fasta.gz ont043.fasta.gz ont044.fasta.gz ont045.fasta.gz ont046.fasta.gz ont047.fasta.gz ont048.fasta.gz ont049.fasta.gz ont050.fasta.gz ont051.fasta.gz ont052.fasta.gz ont053.fasta.gz ont054.fasta.gz ont055.fasta.gz ont056.fasta.gz ont057.fasta.gz ont058.fasta.gz ont059.fasta.gz ont060.fasta.gz ont061.fasta.gz ont062.fasta.gz ont063.fasta.gz ont064.fasta.gz ont065.fasta.gz ont066.fasta.gz ont067.fasta.gz ont068.fasta.gz ont069.fasta.gz ont070.fasta.gz ont071.fasta.gz ont072.fasta.gz ont073.fasta.gz ont074.fasta.gz ont075.fasta.gz ont076.fasta.gz ont077.fasta.gz ont078.fasta.gz ont079.fasta.gz ont080.fasta.gz ont081.fasta.gz ont082.fasta.gz ont083.fasta.gz ont084.fasta.gz ont085.fasta.gz ont086.fasta.gz ont087.fasta.gz |awk -v SEQ="" '{ if (match(\$1, ">") && \$1 != NAME) { if (SEQ != "") { print NAME; print SEQ; } SEQ=""; NAME=\$1; } else { SEQ=SEQ""\$1;} } END { print NAME; print SEQ}' | tr -s ACGT > tip_reads_compressed.fasta
rm -f ont001.fasta.gz ont002.fasta.gz ont003.fasta.gz ont004.fasta.gz ont005.fasta.gz ont006.fasta.gz ont007.fasta.gz ont008.fasta.gz ont009.fasta.gz ont010.fasta.gz ont011.fasta.gz ont012.fasta.gz ont013.fasta.gz ont014.fasta.gz ont015.fasta.gz ont016.fasta.gz ont017.fasta.gz ont018.fasta.gz ont019.fasta.gz ont020.fasta.gz ont021.fasta.gz ont022.fasta.gz ont023.fasta.gz ont024.fasta.gz ont025.fasta.gz ont026.fasta.gz ont027.fasta.gz ont028.fasta.gz ont029.fasta.gz ont030.fasta.gz ont031.fasta.gz ont032.fasta.gz ont033.fasta.gz ont034.fasta.gz ont035.fasta.gz ont036.fasta.gz ont037.fasta.gz ont038.fasta.gz ont039.fasta.gz ont040.fasta.gz ont041.fasta.gz ont042.fasta.gz ont043.fasta.gz ont044.fasta.gz ont045.fasta.gz ont046.fasta.gz ont047.fasta.gz ont048.fasta.gz ont049.fasta.gz ont050.fasta.gz ont051.fasta.gz ont052.fasta.gz ont053.fasta.gz ont054.fasta.gz ont055.fasta.gz ont056.fasta.gz ont057.fasta.gz ont058.fasta.gz ont059.fasta.gz ont060.fasta.gz ont061.fasta.gz ont062.fasta.gz ont063.fasta.gz ont064.fasta.gz ont065.fasta.gz ont066.fasta.gz ont067.fasta.gz ont068.fasta.gz ont069.fasta.gz ont070.fasta.gz ont071.fasta.gz ont072.fasta.gz ont073.fasta.gz ont074.fasta.gz ont075.fasta.gz ont076.fasta.gz ont077.fasta.gz ont078.fasta.gz ont079.fasta.gz ont080.fasta.gz ont081.fasta.gz ont082.fasta.gz ont083.fasta.gz ont084.fasta.gz ont085.fasta.gz ont086.fasta.gz ont087.fasta.gz

cat ../2-processGraph/unitig-unrolled-hifi-resolved.gfa |awk '{ if (match(\$1, "^S")) { print ">"\$2; print \$3 } }' |fold -b > tips.fasta

bases=\`expr 3000000000 / 2 \`
 /projects/academic/omergokc/Luane/conda/envs/herro/lib/verkko/scripts/fasta_partition.py \\
  partition split/ont \$bases 150000 0 \\
  tip_reads_compressed.fasta \\
&& \\
touch ../3-alignTips/splitONT.finished
EOF

chmod +x ./splitONT.sh

./splitONT.sh > ../3-alignTips/splitONT.err 2>&1
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-09-02T174129.822291.snakemake.log

```
Attached is the entire error/log file.
[verkko.err.txt](https://github.com/user-attachments/files/16897015/verkko.err.txt)

I know that my Meryl files look good - and I don't think that is the problem because I think that is a step further. 

```
(herro) luanejan@vortex-future:/projects/academic/omergokc/Luane/HG01946/verkko/diploid$ meryl print maternal_compressed.k30.hapmer.meryl | head

Found 1 command tree.

PROCESSING TREE #1 using 20 threads.
  opLessThan
    maternal_compressed.k30.hapmer.meryl
    print to (stdout)
ACACACACACACACACACACATACTGACGA	12
ACACACACACACACACACACATAGCGCTCT	12
ACACACACACACACACACACATCTGACTGC	6
ACACACACACACACACACACATCTGCGTCA	15
ACACACACACACACACACACATGCTCATCG	11
ACACACACACACACACACACATGCGTGTAT	14
ACACACACACACACACACACAGTACGCTCT	18
ACACACACACACACACACACAGTCGTATGT	20
ACACACACACACACACACACTACTGTCGCT	8
ACACACACACACACACACACTACGTATCAT	10

(herro) luanejan@vortex-future:/projects/academic/omergokc/Luane/HG01946/verkko/diploid$ meryl print paternal_compressed.k30.hapmer.meryl | head

Found 1 command tree.

PROCESSING TREE #1 using 20 threads.
  opLessThan
    paternal_compressed.k30.hapmer.meryl
    print to (stdout)
ACACACACACACACACACACACTGTGACGC	6
ACACACACACACACACACACATCGCGTGTA	18
ACACACACACACACACACACATCGTACGTG	22
ACACACACACACACACACACATGCTCGAGT	10
ACACACACACACACACACACATGCTCGTCT	6
ACACACACACACACACACACATGCTGAGCG	8
ACACACACACACACACACACATGTGCTAGC	14
ACACACACACACACACACACAGAGCGCGTA	7
ACACACACACACACACACACAGAGTCGTGC	20
ACACACACACACACACACACAGTACACGCT	13
```

I am not sure what is happening. Do you have any ideas? Also, I tried to upload the inputs and files Im using, but could not do it through here. Do you usually have a platform you use to share these in case I need?

Thank you!

**Comment by skoren** [comment]
I suspect some of the outputs were removed during the cleanup of the previous run and so are causing this step to fail. What does the `3-alignTips/splitONT.err` script report?

**Comment by luanelandau** [comment]
The 3-alignTips/splitONT.err script is as follows:

`./splitONT.sh: 2: set: Illegal option -o pipefail`
 
I have tried to change the script "/bash" like suggested in #185 but it did not work. Still gave me the same error.

I have updated the verkko version to 2.2 (you were right, I was using an old version of verkko), and I deleted the --cleanup option. I am waiting for it to run now and will follow up.

**Comment by luanelandau** [comment]
Worked now! Thank you once again.

**Comment by dazhuang420** [comment]
Thank you very much. I look forward to your reply. I am now completing processONT.sh step by step, and now I have succeeded in Step 4b. Strangely, if I run processONT.sh directly, I will get an error:
Traceback (most recent call last):
File "/public/home/caijing_lab/zhaodazhuang/anaconda3/lib/verkko/scripts/add_hairpin_uniques.py", line 70, in <module>
assert node in nodelens
^^^^^^^^^^^^^^^^
AssertionError
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
FileNotFoundError: [Errno 2] No such file or directory
/opt/gridview//pbs/dispatcher/mom_priv/jobs/8924815.admin1.SC: line 67: bridges.txt: No such file or directory
Traceback (most recent call last):
File "/public/home/caijing_lab/zhaodazhuang/anaconda3/lib/verkko/scripts/fix_diploid_paths.py", line 85, in <module>
with open(counted_paths_file) as f:
^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'bridges.txt'
Traceback (most recent call last):
File "/public/home/caijing_lab/zhaodazhuang/anaconda3/lib/verkko/scripts/forbid_unbridged_tangles.py", line 8, in <module>
picked_connections_file = sys.argv[4]
~~~~~~~~^^^
IndexError: list index out of range
So now I can only run the program step by step. The problem found should be between 4b and step 5:/public/home/caijing _ lab/zhaodazhuang/anaconda3/lib/verkko/scripts/ add_hairpin_uniques.py unique_nodes_diploidfix.txt hifi-nodecov-gapped-unitig-unrolled-hifi-resolved.csv < gapped-unitig-unrolled-hifi-resolved.gfa \
> unique_nodes_hairpinfix.txt will run with an error message:
Traceback (most recent call last):
File "/public/home/caijing_lab/zhaodazhuang/anaconda3/lib/verkko/scripts/add_hairpin_uniques.py", line 70, in <module>
assert node in nodelens
^^^^^^^^^^^^^^^^
AssertionError
I hope you can help me solve it, thank you very much ~
