### ISSUE TITLE
AssertionError in pop_bubbles_coverage_based

### ISSUE THREAD

**Issue by baozg** [marbl/verkko#42]
Hi, 

After `estimate_unique_local` running for 16 hour with 800Mb genome (#40, this data), but it throw error in the `5-untip/pop_bubbles_coverage_based`

```bash
average coverage 20.735745793373216
Traceback (most recent call last):
  File "/public10/home/sci0009/miniconda3/envs/snakemake/lib/verkko/scripts/pop_bubbles_coverage_based.py", line 267, in <module>
    try_pop_tip(">" + node, edges, coverage, removed_nodes, removed_edges, avg_coverage*.75)
  File "/public10/home/sci0009/miniconda3/envs/snakemake/lib/verkko/scripts/pop_bubbles_coverage_based.py", line 142, in try_pop_tip
    assert node[1:] in coverage
AssertionError
```

Here is the `hifi-resloved.gfa`.

![image](https://user-images.githubusercontent.com/20680150/151320103-fb900e02-7911-4120-8077-d6959a81396d.png)

**Comment by maickrau** [comment]
The script had issues with nodes whose hifi coverage was missing, could you try again with commit fd7725e

**Comment by baozg** [comment]
It worked. I can close this.
