### ISSUE TITLE
TypeError: '>' not supported between instances of 'TBDString' and 'int' in dryrun

### ISSUE THREAD

**Issue by brianwalenz** [marbl/verkko#82]
A `--dryrun` generated the following error when I removed `3-align/split` and `7-consensus` (and all the normal verkko outputs) from a finished run.  This seems to affect only a dryrun; running without that option does work (and rebuilds 3-align/split, regenerates the alignments and packages, and computes consensus).

To reproduce: `rm -rf 3-align/split 7-consensus assembly*`

```
[Tue Jul  5 14:36:35 2022]
checkpoint buildPackages:
    input: /devel/verkko-test/../verkko-regression/reads/ecoli_hifi_subset24x.fastq.gz, 6-layoutContigs/unitig-popped.layout, 7-consensus/ont_subset.fasta.gz
    output: 7-consensus/packages.tigName_to_ID.map, 7-consensus/packages.finished, 7-consensus/packages.report
    log: 7-consensus/buildPackages.err
    jobid: 21
    reason: Missing output files: 7-consensus/packages.finished, 7-consensus/packages.tigName_to_ID.map; Input files updated by another job: 6-layoutContigs/unitig-popped.layout, 7-consensus/ont_subset.fasta.gz
    threads: 8
    resources: tmpdir=/tmp, job_id=1, n_cpus=8, mem_gb=<TBD>, time_h=24
Downstream jobs will be updated after completion.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/snakemake/__init__.py", line 722, in snakemake
    success = workflow.execute(
  File "/usr/local/lib/python3.8/site-packages/snakemake/workflow.py", line 1112, in execute
    success = self.scheduler.schedule()
  File "/usr/local/lib/python3.8/site-packages/snakemake/scheduler.py", line 421, in schedule
    self._finish_jobs()
  File "/usr/local/lib/python3.8/site-packages/snakemake/scheduler.py", line 536, in _finish_jobs
    self._free_resources(job)
  File "/usr/local/lib/python3.8/site-packages/snakemake/scheduler.py", line 576, in _free_resources
    value = self.calc_resource(name, value)
  File "/usr/local/lib/python3.8/site-packages/snakemake/scheduler.py", line 878, in calc_resource
    if value > gres:
TypeError: '>' not supported between instances of 'TBDString' and 'int'
```

**Comment by brianwalenz** [comment]
Probably fixed by 1595d30ff175ff333be060f561eef984ec3e5ae7.
